### ISSUE TITLE
a.b.c.d などの時も警告を出せるようにする

### ISSUE THREAD

**Issue by keyl0ve** [Keyl0ve/termcheck#1]
## 現状
a.b の時しかできていない
user.ReadData() -> ok
user.ReadUser() -> ng

## 改善点
a.b.c.d など複数あるときも警告を出せるように
user.Read().ToString() -> ok
user.Read().UserString() -> ng

**Comment by Keyl0ve** [comment]
[fix: 再帰で呼べるように関数を修正](https://github.com/Keyl0ve/termcheck/commit/74ed69ebe79a6ea530d4230afa3a1a67c9190af7)
こちらで対応
